An exception occured in <%= PP.pp(@processor, '') -%>!

<%= @message %>

<%= @error.class.name -%>: <%= @error.message %>

<%= @error.backtrace.join("\n\t") %>
